// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"abc.com/todo/v1/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/todo",
				Handler: addTodoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/todo",
				Handler: getTodoHandler(serverCtx),
			},
		},
	)
}
